2020-08-10 16:02:29.929184 (MainThread): Running with dbt=0.17.2
2020-08-10 16:02:30.891370 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.generate.GenerateTask'>, compile=True, debug=False, exclude=None, log_cache_events=False, log_format='default', models=None, partial_parse=None, profile=None, profiles_dir='/Users/olivierdupuis/.dbt', project_dir=None, record_timing_info=None, rpc_method='docs.generate', single_threaded=False, strict=False, target=None, test_new_parser=False, threads=None, use_cache=True, vars='{}', version_check=True, warn_error=False, which='generate', write_json=True)
2020-08-10 16:02:30.893008 (MainThread): Tracking: tracking
2020-08-10 16:02:30.893452 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111b9a5d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x111b9ae90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110259e90>]}
2020-08-10 16:02:30.919743 (MainThread): Partial parsing not enabled
2020-08-10 16:02:30.922759 (MainThread): Parsing macros/core.sql
2020-08-10 16:02:30.929277 (MainThread): Parsing macros/materializations/helpers.sql
2020-08-10 16:02:30.939474 (MainThread): Parsing macros/materializations/snapshot/snapshot_merge.sql
2020-08-10 16:02:30.942077 (MainThread): Parsing macros/materializations/snapshot/strategies.sql
2020-08-10 16:02:30.964351 (MainThread): Parsing macros/materializations/snapshot/snapshot.sql
2020-08-10 16:02:31.003682 (MainThread): Parsing macros/materializations/seed/seed.sql
2020-08-10 16:02:31.030371 (MainThread): Parsing macros/materializations/incremental/helpers.sql
2020-08-10 16:02:31.033469 (MainThread): Parsing macros/materializations/incremental/incremental.sql
2020-08-10 16:02:31.041970 (MainThread): Parsing macros/materializations/common/merge.sql
2020-08-10 16:02:31.059864 (MainThread): Parsing macros/materializations/table/table.sql
2020-08-10 16:02:31.069266 (MainThread): Parsing macros/materializations/view/view.sql
2020-08-10 16:02:31.077644 (MainThread): Parsing macros/materializations/view/create_or_replace_view.sql
2020-08-10 16:02:31.084168 (MainThread): Parsing macros/etc/get_custom_alias.sql
2020-08-10 16:02:31.085751 (MainThread): Parsing macros/etc/query.sql
2020-08-10 16:02:31.088199 (MainThread): Parsing macros/etc/is_incremental.sql
2020-08-10 16:02:31.090914 (MainThread): Parsing macros/etc/datetime.sql
2020-08-10 16:02:31.102727 (MainThread): Parsing macros/etc/get_custom_schema.sql
2020-08-10 16:02:31.105780 (MainThread): Parsing macros/etc/get_custom_database.sql
2020-08-10 16:02:31.108275 (MainThread): Parsing macros/adapters/common.sql
2020-08-10 16:02:31.171648 (MainThread): Parsing macros/schema_tests/relationships.sql
2020-08-10 16:02:31.173742 (MainThread): Parsing macros/schema_tests/not_null.sql
2020-08-10 16:02:31.175595 (MainThread): Parsing macros/schema_tests/unique.sql
2020-08-10 16:02:31.177607 (MainThread): Parsing macros/schema_tests/accepted_values.sql
2020-08-10 16:02:31.181436 (MainThread): Parsing macros/catalog.sql
2020-08-10 16:02:31.184666 (MainThread): Parsing macros/adapters.sql
2020-08-10 16:02:31.213722 (MainThread): Parsing macros/materializations/merge.sql
2020-08-10 16:02:31.216672 (MainThread): Parsing macros/materializations/view.sql
2020-08-10 16:02:31.218919 (MainThread): Parsing macros/materializations/table.sql
2020-08-10 16:02:31.224374 (MainThread): Parsing macros/materializations/incremental.sql
2020-08-10 16:02:31.256862 (MainThread): Partial parsing not enabled
2020-08-10 16:02:31.305287 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.wh_product_sessions_fact".
2020-08-10 16:02:31.305466 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:02:31.341758 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.wh_product_users_dim".
2020-08-10 16:02:31.341921 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:02:31.356468 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.wh_product_events_fact".
2020-08-10 16:02:31.356645 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:02:31.372871 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.stg_product_sessions".
2020-08-10 16:02:31.373050 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:02:31.386774 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.stg_product_pages".
2020-08-10 16:02:31.386948 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:02:31.400315 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.stg_product_tracks".
2020-08-10 16:02:31.400458 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:02:31.413413 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.int_product_events".
2020-08-10 16:02:31.413558 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:02:31.426771 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.int_product_sessions".
2020-08-10 16:02:31.426901 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:02:31.438979 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.int_product_users".
2020-08-10 16:02:31.439117 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:02:31.451085 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11239efd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1123d8110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1123d8390>]}
2020-08-10 16:02:31.451451 (MainThread): Flushing usage events
2020-08-10 16:02:32.206704 (MainThread): Connection 'model.dbt_product_warehouse.int_product_users' was properly closed.
2020-08-10 16:02:32.206970 (MainThread): Encountered an error:
2020-08-10 16:02:32.207163 (MainThread): Compilation Error
  Error reading dbt_product_warehouse: staging/product/sources.yml - Runtime Error
    Syntax error near line 2
    ------------------------------
    1  | - name: segment
    2  |     database: segment
    3  |     schema: product
    4  | 
    5  |     freshness:
    
    Raw Error:
    ------------------------------
    mapping values are not allowed in this context
      in "<unicode string>", line 2, column 13
2020-08-10 16:02:32.216179 (MainThread): Traceback (most recent call last):
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/clients/yaml_helper.py", line 62, in load_yaml_text
    return safe_load(contents)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/clients/yaml_helper.py", line 57, in safe_load
    return yaml.load(contents, Loader=YamlLoader)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext/_yaml.pyx", line 774, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 851, in _yaml.CParser._compose_sequence_node
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.scanner.ScannerError: mapping values are not allowed in this context
  in "<unicode string>", line 2, column 13

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/schemas.py", line 213, in _yaml_from_file
    return load_yaml_text(source_file.contents)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/clients/yaml_helper.py", line 69, in load_yaml_text
    raise dbt.exceptions.ValidationException(error)
dbt.exceptions.ValidationException: Runtime Error
  Syntax error near line 2
  ------------------------------
  1  | - name: segment
  2  |     database: segment
  3  |     schema: product
  4  | 
  5  |     freshness:
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 2, column 13

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/main.py", line 81, in main
    results, succeeded = handle_and_check(args)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/main.py", line 159, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/main.py", line 212, in run_from_args
    results = task.run()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/generate.py", line 215, in run
    compile_results = CompileTask.run(self)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 390, in run
    self._runtime_initialize()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 103, in _runtime_initialize
    super()._runtime_initialize()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 71, in _runtime_initialize
    self.load_manifest()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 60, in load_manifest
    self.manifest = get_full_manifest(self.config)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/perf_utils.py", line 23, in get_full_manifest
    return load_manifest(config, internal, set_header)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 641, in load_manifest
    return ManifestLoader.load_all(config, internal_manifest, macro_hook)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 356, in load_all
    loader.load(internal_manifest=internal_manifest)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 212, in load
    self.parse_project(project, macro_manifest, old_results)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 186, in parse_project
    self.parse_with_cache(path, parser, old_results)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 142, in parse_with_cache
    parser.parse_file(block)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/schemas.py", line 506, in parse_file
    dct = self._yaml_from_file(block.file)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/schemas.py", line 218, in _yaml_from_file
    .format(self.project.project_name, path, reason)
dbt.exceptions.CompilationException: Compilation Error
  Error reading dbt_product_warehouse: staging/product/sources.yml - Runtime Error
    Syntax error near line 2
    ------------------------------
    1  | - name: segment
    2  |     database: segment
    3  |     schema: product
    4  | 
    5  |     freshness:
    
    Raw Error:
    ------------------------------
    mapping values are not allowed in this context
      in "<unicode string>", line 2, column 13

2020-08-10 16:03:29.946728 (MainThread): Running with dbt=0.17.2
2020-08-10 16:03:30.294209 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.generate.GenerateTask'>, compile=True, debug=False, exclude=None, log_cache_events=False, log_format='default', models=None, partial_parse=None, profile=None, profiles_dir='/Users/olivierdupuis/.dbt', project_dir=None, record_timing_info=None, rpc_method='docs.generate', single_threaded=False, strict=False, target=None, test_new_parser=False, threads=None, use_cache=True, vars='{}', version_check=True, warn_error=False, which='generate', write_json=True)
2020-08-10 16:03:30.295131 (MainThread): Tracking: tracking
2020-08-10 16:03:30.295528 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10a1ce210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bb49510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10bb49750>]}
2020-08-10 16:03:30.319451 (MainThread): Partial parsing not enabled
2020-08-10 16:03:30.321584 (MainThread): Parsing macros/core.sql
2020-08-10 16:03:30.327560 (MainThread): Parsing macros/materializations/helpers.sql
2020-08-10 16:03:30.338028 (MainThread): Parsing macros/materializations/snapshot/snapshot_merge.sql
2020-08-10 16:03:30.340448 (MainThread): Parsing macros/materializations/snapshot/strategies.sql
2020-08-10 16:03:30.362212 (MainThread): Parsing macros/materializations/snapshot/snapshot.sql
2020-08-10 16:03:30.400245 (MainThread): Parsing macros/materializations/seed/seed.sql
2020-08-10 16:03:30.428972 (MainThread): Parsing macros/materializations/incremental/helpers.sql
2020-08-10 16:03:30.431364 (MainThread): Parsing macros/materializations/incremental/incremental.sql
2020-08-10 16:03:30.439471 (MainThread): Parsing macros/materializations/common/merge.sql
2020-08-10 16:03:30.456658 (MainThread): Parsing macros/materializations/table/table.sql
2020-08-10 16:03:30.465009 (MainThread): Parsing macros/materializations/view/view.sql
2020-08-10 16:03:30.472958 (MainThread): Parsing macros/materializations/view/create_or_replace_view.sql
2020-08-10 16:03:30.478901 (MainThread): Parsing macros/etc/get_custom_alias.sql
2020-08-10 16:03:30.480015 (MainThread): Parsing macros/etc/query.sql
2020-08-10 16:03:30.481297 (MainThread): Parsing macros/etc/is_incremental.sql
2020-08-10 16:03:30.483595 (MainThread): Parsing macros/etc/datetime.sql
2020-08-10 16:03:30.495569 (MainThread): Parsing macros/etc/get_custom_schema.sql
2020-08-10 16:03:30.497977 (MainThread): Parsing macros/etc/get_custom_database.sql
2020-08-10 16:03:30.499979 (MainThread): Parsing macros/adapters/common.sql
2020-08-10 16:03:30.560805 (MainThread): Parsing macros/schema_tests/relationships.sql
2020-08-10 16:03:30.562257 (MainThread): Parsing macros/schema_tests/not_null.sql
2020-08-10 16:03:30.563330 (MainThread): Parsing macros/schema_tests/unique.sql
2020-08-10 16:03:30.564602 (MainThread): Parsing macros/schema_tests/accepted_values.sql
2020-08-10 16:03:30.567277 (MainThread): Parsing macros/catalog.sql
2020-08-10 16:03:30.569467 (MainThread): Parsing macros/adapters.sql
2020-08-10 16:03:30.596173 (MainThread): Parsing macros/materializations/merge.sql
2020-08-10 16:03:30.598539 (MainThread): Parsing macros/materializations/view.sql
2020-08-10 16:03:30.599995 (MainThread): Parsing macros/materializations/table.sql
2020-08-10 16:03:30.604540 (MainThread): Parsing macros/materializations/incremental.sql
2020-08-10 16:03:30.636146 (MainThread): Partial parsing not enabled
2020-08-10 16:03:30.677323 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.wh_product_sessions_fact".
2020-08-10 16:03:30.677483 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:03:30.711794 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.wh_product_users_dim".
2020-08-10 16:03:30.711949 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:03:30.725229 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.wh_product_events_fact".
2020-08-10 16:03:30.725363 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:03:30.740320 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.stg_product_sessions".
2020-08-10 16:03:30.740463 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:03:30.752945 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.stg_product_pages".
2020-08-10 16:03:30.753065 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:03:30.764802 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.stg_product_tracks".
2020-08-10 16:03:30.764918 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:03:30.776547 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.int_product_events".
2020-08-10 16:03:30.776659 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:03:30.790995 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.int_product_sessions".
2020-08-10 16:03:30.791163 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:03:30.803109 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.int_product_users".
2020-08-10 16:03:30.803267 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:03:30.814964 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c364c90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c395dd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c395c50>]}
2020-08-10 16:03:30.815198 (MainThread): Flushing usage events
2020-08-10 16:03:31.114565 (MainThread): Connection 'model.dbt_product_warehouse.int_product_users' was properly closed.
2020-08-10 16:03:31.114831 (MainThread): Encountered an error:
2020-08-10 16:03:31.115028 (MainThread): Compilation Error
  Error reading dbt_product_warehouse: staging/product/sources.yml - Runtime Error
    Syntax error near line 2
    ------------------------------
    1  | - name: segment
    2  |     database: segment
    3  |     schema: product
    4  | 
    5  |     tables:
    
    Raw Error:
    ------------------------------
    mapping values are not allowed in this context
      in "<unicode string>", line 2, column 13
2020-08-10 16:03:31.117642 (MainThread): Traceback (most recent call last):
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/clients/yaml_helper.py", line 62, in load_yaml_text
    return safe_load(contents)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/clients/yaml_helper.py", line 57, in safe_load
    return yaml.load(contents, Loader=YamlLoader)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext/_yaml.pyx", line 774, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 851, in _yaml.CParser._compose_sequence_node
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.scanner.ScannerError: mapping values are not allowed in this context
  in "<unicode string>", line 2, column 13

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/schemas.py", line 213, in _yaml_from_file
    return load_yaml_text(source_file.contents)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/clients/yaml_helper.py", line 69, in load_yaml_text
    raise dbt.exceptions.ValidationException(error)
dbt.exceptions.ValidationException: Runtime Error
  Syntax error near line 2
  ------------------------------
  1  | - name: segment
  2  |     database: segment
  3  |     schema: product
  4  | 
  5  |     tables:
  
  Raw Error:
  ------------------------------
  mapping values are not allowed in this context
    in "<unicode string>", line 2, column 13

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/main.py", line 81, in main
    results, succeeded = handle_and_check(args)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/main.py", line 159, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/main.py", line 212, in run_from_args
    results = task.run()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/generate.py", line 215, in run
    compile_results = CompileTask.run(self)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 390, in run
    self._runtime_initialize()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 103, in _runtime_initialize
    super()._runtime_initialize()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 71, in _runtime_initialize
    self.load_manifest()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 60, in load_manifest
    self.manifest = get_full_manifest(self.config)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/perf_utils.py", line 23, in get_full_manifest
    return load_manifest(config, internal, set_header)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 641, in load_manifest
    return ManifestLoader.load_all(config, internal_manifest, macro_hook)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 356, in load_all
    loader.load(internal_manifest=internal_manifest)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 212, in load
    self.parse_project(project, macro_manifest, old_results)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 186, in parse_project
    self.parse_with_cache(path, parser, old_results)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 142, in parse_with_cache
    parser.parse_file(block)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/schemas.py", line 506, in parse_file
    dct = self._yaml_from_file(block.file)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/schemas.py", line 218, in _yaml_from_file
    .format(self.project.project_name, path, reason)
dbt.exceptions.CompilationException: Compilation Error
  Error reading dbt_product_warehouse: staging/product/sources.yml - Runtime Error
    Syntax error near line 2
    ------------------------------
    1  | - name: segment
    2  |     database: segment
    3  |     schema: product
    4  | 
    5  |     tables:
    
    Raw Error:
    ------------------------------
    mapping values are not allowed in this context
      in "<unicode string>", line 2, column 13

2020-08-10 16:05:25.547785 (MainThread): Running with dbt=0.17.2
2020-08-10 16:05:26.119094 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.generate.GenerateTask'>, compile=True, debug=False, exclude=None, log_cache_events=False, log_format='default', models=None, partial_parse=None, profile=None, profiles_dir='/Users/olivierdupuis/.dbt', project_dir=None, record_timing_info=None, rpc_method='docs.generate', single_threaded=False, strict=False, target=None, test_new_parser=False, threads=None, use_cache=True, vars='{}', version_check=True, warn_error=False, which='generate', write_json=True)
2020-08-10 16:05:26.120446 (MainThread): Tracking: tracking
2020-08-10 16:05:26.120963 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107226e10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ba0910>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ba0810>]}
2020-08-10 16:05:26.145231 (MainThread): Partial parsing not enabled
2020-08-10 16:05:26.147594 (MainThread): Parsing macros/core.sql
2020-08-10 16:05:26.153769 (MainThread): Parsing macros/materializations/helpers.sql
2020-08-10 16:05:26.163596 (MainThread): Parsing macros/materializations/snapshot/snapshot_merge.sql
2020-08-10 16:05:26.166017 (MainThread): Parsing macros/materializations/snapshot/strategies.sql
2020-08-10 16:05:26.186691 (MainThread): Parsing macros/materializations/snapshot/snapshot.sql
2020-08-10 16:05:26.222603 (MainThread): Parsing macros/materializations/seed/seed.sql
2020-08-10 16:05:26.249810 (MainThread): Parsing macros/materializations/incremental/helpers.sql
2020-08-10 16:05:26.252540 (MainThread): Parsing macros/materializations/incremental/incremental.sql
2020-08-10 16:05:26.261178 (MainThread): Parsing macros/materializations/common/merge.sql
2020-08-10 16:05:26.280823 (MainThread): Parsing macros/materializations/table/table.sql
2020-08-10 16:05:26.289894 (MainThread): Parsing macros/materializations/view/view.sql
2020-08-10 16:05:26.298229 (MainThread): Parsing macros/materializations/view/create_or_replace_view.sql
2020-08-10 16:05:26.304859 (MainThread): Parsing macros/etc/get_custom_alias.sql
2020-08-10 16:05:26.306568 (MainThread): Parsing macros/etc/query.sql
2020-08-10 16:05:26.308224 (MainThread): Parsing macros/etc/is_incremental.sql
2020-08-10 16:05:26.311123 (MainThread): Parsing macros/etc/datetime.sql
2020-08-10 16:05:26.323030 (MainThread): Parsing macros/etc/get_custom_schema.sql
2020-08-10 16:05:26.325793 (MainThread): Parsing macros/etc/get_custom_database.sql
2020-08-10 16:05:26.328606 (MainThread): Parsing macros/adapters/common.sql
2020-08-10 16:05:26.388969 (MainThread): Parsing macros/schema_tests/relationships.sql
2020-08-10 16:05:26.391255 (MainThread): Parsing macros/schema_tests/not_null.sql
2020-08-10 16:05:26.393548 (MainThread): Parsing macros/schema_tests/unique.sql
2020-08-10 16:05:26.395698 (MainThread): Parsing macros/schema_tests/accepted_values.sql
2020-08-10 16:05:26.399691 (MainThread): Parsing macros/catalog.sql
2020-08-10 16:05:26.402802 (MainThread): Parsing macros/adapters.sql
2020-08-10 16:05:26.429302 (MainThread): Parsing macros/materializations/merge.sql
2020-08-10 16:05:26.432303 (MainThread): Parsing macros/materializations/view.sql
2020-08-10 16:05:26.434317 (MainThread): Parsing macros/materializations/table.sql
2020-08-10 16:05:26.439314 (MainThread): Parsing macros/materializations/incremental.sql
2020-08-10 16:05:26.473020 (MainThread): Partial parsing not enabled
2020-08-10 16:05:26.513130 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.wh_product_sessions_fact".
2020-08-10 16:05:26.513284 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:05:26.547931 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.wh_product_users_dim".
2020-08-10 16:05:26.548084 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:05:26.561730 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.wh_product_events_fact".
2020-08-10 16:05:26.561886 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:05:26.576633 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.stg_product_sessions".
2020-08-10 16:05:26.576750 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:05:26.588921 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.stg_product_pages".
2020-08-10 16:05:26.589071 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:05:26.601787 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.stg_product_tracks".
2020-08-10 16:05:26.601946 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:05:26.614497 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.int_product_events".
2020-08-10 16:05:26.614646 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:05:26.627888 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.int_product_sessions".
2020-08-10 16:05:26.628030 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:05:26.639731 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.int_product_users".
2020-08-10 16:05:26.639870 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:05:26.729498 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094d3210>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1093c4310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109525510>]}
2020-08-10 16:05:26.729782 (MainThread): Flushing usage events
2020-08-10 16:05:27.086089 (MainThread): Connection 'model.dbt_product_warehouse.int_product_users' was properly closed.
2020-08-10 16:05:27.086350 (MainThread): Encountered an error:
2020-08-10 16:05:27.086548 (MainThread): Compilation Error in model stg_product_sessions (models/staging/product/stg_product_sessions.sql)
  Model 'model.dbt_product_warehouse.stg_product_sessions' (models/staging/product/stg_product_sessions.sql) depends on a node named 'segment_web_sessions' which was not found
2020-08-10 16:05:27.093905 (MainThread): Traceback (most recent call last):
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/main.py", line 81, in main
    results, succeeded = handle_and_check(args)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/main.py", line 159, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/main.py", line 212, in run_from_args
    results = task.run()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/generate.py", line 215, in run
    compile_results = CompileTask.run(self)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 390, in run
    self._runtime_initialize()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 103, in _runtime_initialize
    super()._runtime_initialize()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 71, in _runtime_initialize
    self.load_manifest()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 60, in load_manifest
    self.manifest = get_full_manifest(self.config)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/perf_utils.py", line 23, in get_full_manifest
    return load_manifest(config, internal, set_header)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 641, in load_manifest
    return ManifestLoader.load_all(config, internal_manifest, macro_hook)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 358, in load_all
    manifest = loader.create_manifest()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 334, in create_manifest
    self.process_manifest(manifest)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 306, in process_manifest
    process_refs(manifest, project_name)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 564, in process_refs
    _process_refs_for_node(manifest, current_project, node)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 548, in _process_refs_for_node
    disabled=(isinstance(target_model, Disabled))
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/utils.py", line 318, in invalid_ref_fail_unless_test
    disabled=disabled,
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/exceptions.py", line 527, in ref_target_not_found
    raise_compiler_error(msg, model)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/exceptions.py", line 396, in raise_compiler_error
    raise CompilationException(msg, node)
dbt.exceptions.CompilationException: Compilation Error in model stg_product_sessions (models/staging/product/stg_product_sessions.sql)
  Model 'model.dbt_product_warehouse.stg_product_sessions' (models/staging/product/stg_product_sessions.sql) depends on a node named 'segment_web_sessions' which was not found

2020-08-10 16:06:11.571088 (MainThread): Running with dbt=0.17.2
2020-08-10 16:06:11.911433 (MainThread): running dbt with arguments Namespace(cls=<class 'dbt.task.generate.GenerateTask'>, compile=True, debug=False, exclude=None, log_cache_events=False, log_format='default', models=None, partial_parse=None, profile=None, profiles_dir='/Users/olivierdupuis/.dbt', project_dir=None, record_timing_info=None, rpc_method='docs.generate', single_threaded=False, strict=False, target=None, test_new_parser=False, threads=None, use_cache=True, vars='{}', version_check=True, warn_error=False, which='generate', write_json=True)
2020-08-10 16:06:11.912437 (MainThread): Tracking: tracking
2020-08-10 16:06:11.912799 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10edb4950>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10edb43d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10ede2090>]}
2020-08-10 16:06:11.935897 (MainThread): Partial parsing not enabled
2020-08-10 16:06:11.937918 (MainThread): Parsing macros/core.sql
2020-08-10 16:06:11.943637 (MainThread): Parsing macros/materializations/helpers.sql
2020-08-10 16:06:11.953475 (MainThread): Parsing macros/materializations/snapshot/snapshot_merge.sql
2020-08-10 16:06:11.955757 (MainThread): Parsing macros/materializations/snapshot/strategies.sql
2020-08-10 16:06:11.976873 (MainThread): Parsing macros/materializations/snapshot/snapshot.sql
2020-08-10 16:06:12.012787 (MainThread): Parsing macros/materializations/seed/seed.sql
2020-08-10 16:06:12.040567 (MainThread): Parsing macros/materializations/incremental/helpers.sql
2020-08-10 16:06:12.043002 (MainThread): Parsing macros/materializations/incremental/incremental.sql
2020-08-10 16:06:12.051315 (MainThread): Parsing macros/materializations/common/merge.sql
2020-08-10 16:06:12.068419 (MainThread): Parsing macros/materializations/table/table.sql
2020-08-10 16:06:12.076741 (MainThread): Parsing macros/materializations/view/view.sql
2020-08-10 16:06:12.084532 (MainThread): Parsing macros/materializations/view/create_or_replace_view.sql
2020-08-10 16:06:12.090588 (MainThread): Parsing macros/etc/get_custom_alias.sql
2020-08-10 16:06:12.091743 (MainThread): Parsing macros/etc/query.sql
2020-08-10 16:06:12.093036 (MainThread): Parsing macros/etc/is_incremental.sql
2020-08-10 16:06:12.094974 (MainThread): Parsing macros/etc/datetime.sql
2020-08-10 16:06:12.106138 (MainThread): Parsing macros/etc/get_custom_schema.sql
2020-08-10 16:06:12.108477 (MainThread): Parsing macros/etc/get_custom_database.sql
2020-08-10 16:06:12.110607 (MainThread): Parsing macros/adapters/common.sql
2020-08-10 16:06:12.172200 (MainThread): Parsing macros/schema_tests/relationships.sql
2020-08-10 16:06:12.173588 (MainThread): Parsing macros/schema_tests/not_null.sql
2020-08-10 16:06:12.174725 (MainThread): Parsing macros/schema_tests/unique.sql
2020-08-10 16:06:12.175997 (MainThread): Parsing macros/schema_tests/accepted_values.sql
2020-08-10 16:06:12.178754 (MainThread): Parsing macros/catalog.sql
2020-08-10 16:06:12.181022 (MainThread): Parsing macros/adapters.sql
2020-08-10 16:06:12.207493 (MainThread): Parsing macros/materializations/merge.sql
2020-08-10 16:06:12.209870 (MainThread): Parsing macros/materializations/view.sql
2020-08-10 16:06:12.211551 (MainThread): Parsing macros/materializations/table.sql
2020-08-10 16:06:12.216167 (MainThread): Parsing macros/materializations/incremental.sql
2020-08-10 16:06:12.249436 (MainThread): Partial parsing not enabled
2020-08-10 16:06:12.293206 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.wh_product_sessions_fact".
2020-08-10 16:06:12.293359 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:06:12.328081 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.wh_product_users_dim".
2020-08-10 16:06:12.328243 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:06:12.342577 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.wh_product_events_fact".
2020-08-10 16:06:12.342724 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:06:12.357358 (MainThread): Acquiring new snowflake connection "model.dbt_product_warehouse.segment_web_sessions".
2020-08-10 16:06:12.357481 (MainThread): Opening a new connection, currently in state init
2020-08-10 16:06:12.367136 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110f23c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110f4ee90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x110f4e6d0>]}
2020-08-10 16:06:12.367439 (MainThread): Flushing usage events
2020-08-10 16:06:12.967417 (MainThread): Connection 'model.dbt_product_warehouse.segment_web_sessions' was properly closed.
2020-08-10 16:06:12.967690 (MainThread): Encountered an error:
2020-08-10 16:06:12.967861 (MainThread): bad operand type for unary -: 'NoneType'
2020-08-10 16:06:12.973171 (MainThread): Traceback (most recent call last):
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/main.py", line 81, in main
    results, succeeded = handle_and_check(args)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/main.py", line 159, in handle_and_check
    task, res = run_from_args(parsed)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/main.py", line 212, in run_from_args
    results = task.run()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/generate.py", line 215, in run
    compile_results = CompileTask.run(self)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 390, in run
    self._runtime_initialize()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 103, in _runtime_initialize
    super()._runtime_initialize()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 71, in _runtime_initialize
    self.load_manifest()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/task/runnable.py", line 60, in load_manifest
    self.manifest = get_full_manifest(self.config)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/perf_utils.py", line 23, in get_full_manifest
    return load_manifest(config, internal, set_header)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 641, in load_manifest
    return ManifestLoader.load_all(config, internal_manifest, macro_hook)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 356, in load_all
    loader.load(internal_manifest=internal_manifest)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 212, in load
    self.parse_project(project, macro_manifest, old_results)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 186, in parse_project
    self.parse_with_cache(path, parser, old_results)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/manifest.py", line 142, in parse_with_cache
    parser.parse_file(block)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/base.py", line 419, in parse_file
    self.parse_node(file_block)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/base.py", line 392, in parse_node
    self.render_update(node, config)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/base.py", line 367, in render_update
    self.render_with_context(node, config)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/parser/base.py", line 279, in render_with_context
    parsed_node.raw_sql, context, parsed_node, capture_macros=True
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/clients/jinja.py", line 577, in get_rendered
    return render_template(template, ctx, node)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/dbt/clients/jinja.py", line 528, in render_template
    return template.render(ctx)
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/olivierdupuis/.pyenv/versions/3.7.4/envs/venv_dbtproductwarehouse/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 11, in top-level template code
TypeError: bad operand type for unary -: 'NoneType'

